name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Install build tools
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build twine

      # Build the distribution files
      - name: Build the package
        run: python -m build

      # Publish to PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
